# encoding: UTF-8
#
# Cookbook Name:: openstack-object-storage
# Attributes:: default
#
# Copyright 2014 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

default['openstack']['object-storage']['service_tenant_name'] = 'service'
default['openstack']['object-storage']['service_user'] = 'swift'
default['openstack']['object-storage']['service_role'] = 'service'

# Default swift user
default['openstack']['object-storage']['user'] = 'swift'
# Default swift group
default['openstack']['object-storage']['group'] = 'swift'
# Default region
default['openstack']['object-storage']['region'] = node['openstack']['region']

# Set to some text value if you want templated config files
# to contain a custom banner at the top of the written file
default['openstack']['object-storage']['custom_template_banner'] = "
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
"

#--------------------
# node/ring settings
#--------------------

default['openstack']['object-storage']['state'] = {}
# Hour to run swift_auditor on storage nodes
default['openstack']['object-storage']['audit_hour'] = '5'
#  Eval-able expression that lists
#   candidate disk nodes for disk probing.  The result should be a hash
#   with keys being the device name (without the leading "/dev/") and a
#   hash block of any extra info associated with the device.  For
#   example: { "sdc" => { "model": "Hitachi 7K3000" }}.  Largely,
#   though, if you are going to make a list of valid devices, you
#   probably know all the valid devices, and don't need to pass any
#   metadata about them, so { "sdc" => {}} is probably enough.  Example
#   expression: Hash[('a'..'f').to_a.collect{|x| [ "sd{x}", {} ]}]
default['openstack']['object-storage']['disk_enum_expr'] = 'node[:block_device]'
# Flag to rebuild rings
default['openstack']['object-storage']['auto_rebuild_rings'] = false
# ip for git builder
default['openstack']['object-storage']['git_builder_ip'] = '127.0.0.1'
# How many server changes require before a rebalance is done
default['openstack']['object-storage']['wait_for'] = 1

# swift_hash_path_suffix and swift_hash_path_prefix are used as part of the
# the hashing algorithm when determining data placement in the cluster.
# These values should remain secret and MUST NOT change
# once a cluster has been deployed.
# Deprecated in juno, use swift_hash_path_prefix
default['openstack']['object-storage']['swift_hash'] = nil
# A value of nil will get the hash from the get_password library method in common
default['openstack']['object-storage']['swift_hash_path_prefix'] = node['openstack']['object-storage']['swift_hash']
default['openstack']['object-storage']['swift_hash_path_suffix'] = nil

# The swift-constraints section sets the basic constraints on data
# saved in the swift cluster. These constraints are automatically
# published by the proxy server in responses to /info requests.

# max_file_size is the largest "normal" object that can be saved in
# the cluster. This is also the limit on the size of each segment of
# a "large" object when using the large object manifest support.
# This value is set in bytes. Setting it to lower than 1MiB will cause
# some tests to fail. It is STRONGLY recommended to leave this value at
# the default (5 * 2**30 + 2).
default['openstack']['object-storage']['max_file_size'] = 5368709122
# max_meta_name_length is the max number of bytes in the utf8 encoding
# of the name portion of a metadata header.
default['openstack']['object-storage']['max_meta_name_length'] = 128
# max_meta_value_length is the max number of bytes in the utf8 encoding
# of a metadata value
default['openstack']['object-storage']['max_meta_value_length'] = 256
# max_meta_count is the max number of metadata keys that can be stored
# on a single account, container, or object
default['openstack']['object-storage']['max_meta_count'] = 90
# max_meta_overall_size is the max number of bytes in the utf8 encoding
# of the metadata (keys + values)
default['openstack']['object-storage']['max_meta_overall_size'] = 4096
# max_header_size is the max number of bytes in the utf8 encoding of each
# header. Using 8192 as default because eventlet use 8192 as max size of
# header line. This value may need to be increased when using identity
# v3 API tokens including more than 7 catalog entries.
# See also include_service_catalog in proxy-server.conf-sample
# (documented in overview_auth.rst)
default['openstack']['object-storage']['max_header_size'] = 8192
# max_object_name_length is the max number of bytes in the utf8 encoding
# of an object name
default['openstack']['object-storage']['max_object_name_length'] = 1024
# container_listing_limit is the default (and max) number of items
# returned for a container listing request
default['openstack']['object-storage']['container_listing_limit'] = 10000
# account_listing_limit is the default (and max) number of items returned
# for an account listing request
default['openstack']['object-storage']['account_listing_limit'] = 10000
# max_account_name_length is the max number of bytes in the utf8 encoding
# of an account name
default['openstack']['object-storage']['max_account_name_length'] = 256
# max_container_name_length is the max number of bytes in the utf8 encoding
# of a container name
default['openstack']['object-storage']['max_container_name_length'] = 256

# Use the openstack-common cookbook databags with the
# following keys:
# secret tokens
#   "swift_hash_path_prefix"
#   "swift_hash_path_suffix"
#   "swift_authkey"
#   "dispersion_auth_key"
#   "dispersion_auth_user"

# The follow swift specific databag support is DEPRECATED.
# we support an optional secret databag where we will retrieve the
# following attributes overriding any default attributes here
#
# {
#   "swift_hash": "107c0568ea84"
#   "swift_authkey": "keW4all"
#   "dispersion_auth_user": "test:test",
#   "dispersion_auth_key": "test"
# }
default['openstack']['object-storage']['swift_secret_databag_name'] = nil

#--------------------
# roles
#--------------------

default['openstack']['object-storage']['setup_chef_role']             = 'os-object-storage-setup'
default['openstack']['object-storage']['management_server_chef_role'] = 'os-object-storage-management'
default['openstack']['object-storage']['proxy_server_chef_role']      = 'os-object-storage-proxy'
default['openstack']['object-storage']['object_server_chef_role']     = 'os-object-storage-object'
default['openstack']['object-storage']['account_server_chef_role']    = 'os-object-storage-account'
default['openstack']['object-storage']['container_server_chef_role']  = 'os-object-storage-container'

#--------------------
# authentication
#--------------------

# Authenitcation mode, either keystone or swauth
default['openstack']['object-storage']['authmode']              = 'keystone'
default['openstack']['object-storage']['authkey']               = nil
default['openstack']['object-storage']['swift_url']             = 'http://127.0.0.1:8080/v1/'
default['openstack']['object-storage']['swauth_url']            = 'http://127.0.0.1:8080/v1/'
default['openstack']['object-storage']['auth_url']              = 'http://127.0.0.1:8080/auth/v1.0'
# Keystone version
default['openstack']['object-storage']['api']['auth']['version'] = node['openstack']['api']['auth']['version']
# Keystone PKI signing directory
default['openstack']['object-storage']['api']['auth']['cache_dir'] = '/var/cache/swift/api'

#---------------------
# dispersion settings
#---------------------

default['openstack']['object-storage']['dispersion']['auth_user'] = nil
default['openstack']['object-storage']['dispersion']['auth_key'] = nil

# settings for the swift ring - these default settings are
# a safe setting for testing but part_power should be set to
# 26 in production to allow a swift cluster with 50,000 spindles
default['openstack']['object-storage']['ring']['part_power'] = 18
# The minimum number of hours before swift is allowed to migrate a partition
default['openstack']['object-storage']['ring']['min_part_hours'] = 1
# How many replicas swift should retain
default['openstack']['object-storage']['ring']['replicas'] = 3
# Zone, will look like "z1" on swift-ring-builder command line
default['openstack']['object-storage']['ring']['zone'] = '1'
# Region, will look like "r1" on swift-ring-builder command line
default['openstack']['object-storage']['ring']['region'] = '1'

#------------------
# statistics
#------------------
# Current statsd cookbook is not supported on rhel platforms
default['openstack']['object-storage']['statistics']['enabled'] = platform_family?('debian')
default['openstack']['object-storage']['statistics']['sample_rate'] = 1

# there are two ways to discover your graphite server ip for
# statsd to periodically publish to.  You can directly set
# the ip below, or leave it set to nil and supply chef with
# the role name of your graphite server and the interface
# name to retrieve the appropriate internal ip address from
#
# if no servers with the role below can be found then
# 127.0.0.1 will be used
default['openstack']['object-storage']['statistics']['graphing_ip'] = nil
default['openstack']['object-storage']['statistics']['graphing_role'] = 'graphite-role'
default['openstack']['object-storage']['statistics']['graphing_interface'] = 'eth0'

# how frequently to run chef instantiated /usr/local/bin/swift_statsd_publish.py
# which publishes dispersion and recon statistics (in minutes)
default['openstack']['object-storage']['statistics']['report_frequency'] = 15

# enable or disable specific portions of generated report
default['openstack']['object-storage']['statistics']['enable_dispersion_report'] = true
default['openstack']['object-storage']['statistics']['enable_recon_report'] = true
default['openstack']['object-storage']['statistics']['enable_disk_report'] = true

# settings for statsd which should be configured to use the local
# statsd daemon that chef will install if statistics are enabled
default['openstack']['object-storage']['statistics']['statsd_host'] = '127.0.0.1'
default['openstack']['object-storage']['statistics']['statsd_port'] = '8125'
default['openstack']['object-storage']['statistics']['statsd_prefix'] = 'openstack.swift'

# paths to the recon cache files
default['openstack']['object-storage']['statistics']['recon_account_cache'] = '/var/cache/swift/account.recon'
default['openstack']['object-storage']['statistics']['recon_container_cache'] = '/var/cache/swift/container.recon'
default['openstack']['object-storage']['statistics']['recon_object_cache'] = '/var/cache/swift/object.recon'

#------------------
# network settings
#------------------

# the cidr configuration items are unimportant for a single server
# configuration, but in a multi-server setup, the cidr should match
# the interface appropriate to that service as they are used to
# resolve the appropriate addresses to use for internode
# communication

# Deprecated in Juno, use Common attributes instead
# proxy servers
default['openstack']['object-storage']['network']['proxy-bind-ip']            = nil
default['openstack']['object-storage']['network']['proxy-bind-port']          = nil
default['openstack']['object-storage']['network']['proxy-cidr']               = '127.0.0.0/8'

# account servers
default['openstack']['object-storage']['network']['account-bind-ip']          = '0.0.0.0'
default['openstack']['object-storage']['network']['account-bind-port']        = '6002'

# container servers
default['openstack']['object-storage']['network']['container-bind-ip']        = '0.0.0.0'
default['openstack']['object-storage']['network']['container-bind-port']      = '6001'

# object servers
default['openstack']['object-storage']['network']['object-bind-ip']           = '0.0.0.0'
default['openstack']['object-storage']['network']['object-bind-port']         = '6000'
default['openstack']['object-storage']['network']['object-cidr']              = '127.0.0.0/8'

#------------------
# sysctl
#------------------

# set sysctl properties for time waits
default['openstack']['sysctl']['net.ipv4.tcp_tw_recycle'] = 1
default['openstack']['sysctl']['net.ipv4.tcp_tw_reuse'] = 1
default['openstack']['sysctl']['net.ipv4.tcp_syncookies'] = 0

# N.B. conntrack_max may also need to be adjusted if
# server is running a stateful firewall

#------------------
# disk search
#------------------

# disk_test_filter is an array of predicates to test against disks to
# determine if a disk should be formatted and configured for swift.
# Each predicate is evaluated in turn, and a false from the predicate
# will result in the disk not being considered as a candidate for
# formatting.
# Each rule gets evaluated with "candidate" set to the device name
# without the leading "/dev/") and info set to the node hash value.
default['openstack']['object-storage']['disk_test_filter'] = [
  'candidate =~ /(sd|hd|xvd|vd)(?!a$)[a-z]+/',
  "File.exist?('/dev/' + candidate)",
  "not system('/sbin/parted /dev/' + candidate + ' -s print | grep linux-swap')",
  "not info.has_key?('removable') or info['removable'] == 0.to_s"]

#-------------------
# template overrides
#-------------------

# account-server

# Use an integer to override the number of pre-forked processes that will
# accept connections.  Zero means no fork. Should default to the number of
# effective cpu cores in the system.  It's worth noting that individual
# workers will # use many eventlet co-routines to service multiple concurrent
# requests.
default['openstack']['object-storage']['account-server']['workers'] = 'auto'

# Maximum number of clients one worker can process simultaneously (it will
# actually accept(2) N + 1). Setting this to one (1) will only handle one request
# at a time, without accepting another request concurrently.  The default is 1024.
default['openstack']['object-storage']['account-server']['max_clients'] = 1024

# Parent directory or where devices are mounted. Default is /srv/node
default['openstack']['object-storage']['account-server']['devices'] = '/srv/node'

# Whether or not check if the devices are mounted to prevent accidentally writing to
# the root device. The default is set to true.
default['openstack']['object-storage']['account-server']['mount_check'] = true

# proxy-server

# Use an integer to override the number of pre-forked processes that will
# accept connections.  Zero means no fork. Should default to the number of
# effective cpu cores in the system.  It's worth noting that individual
# workers will # use many eventlet co-routines to service multiple concurrent
# requests.
default['openstack']['object-storage']['proxy-server']['workers'] = 'auto'

# Maximum number of clients one worker can process simultaneously (it will
# actually accept(2) N + 1). Setting this to one (1) will only handle one request
# at a time, without accepting another request concurrently.  The default is 1024.
default['openstack']['object-storage']['proxy-server']['max_clients'] = 1024

# Request timeout to external services. The default is 10 seconds.
default['openstack']['object-storage']['proxy-server']['node_timeout'] = 10

# enable or disable formpost
default['openstack']['object-storage']['formpost']['enabled'] = false

# enable or disable tempurl
default['openstack']['object-storage']['tempurl']['enabled'] = false

# The headers to remove from incoming requests. Simply a whitespace delimited
# list of header names and names can optionally end with '*' to indicate a
# prefix match. incoming_allow_headers is a list of exceptions to these
# removals.
default['openstack']['object-storage']['tempurl']['incoming_remove_headers'] = 'x-timestamp'

# The headers allowed as exceptions to incoming_remove_headers. Simply a
# whitespace delimited list of header names and names can optionally end with
# '*' to indicate a prefix match.
default['openstack']['object-storage']['tempurl']['incoming_allow_headers'] = ''

# The headers to remove from outgoing responses. Simply a whitespace delimited
# list of header names and names can optionally end with '*' to indicate a
# prefix match. outgoing_allow_headers is a list of exceptions to these
# removals.
default['openstack']['object-storage']['tempurl']['outgoing_remove_headers'] = 'x-object-meta-*'

# The headers allowed as exceptions to outgoing_remove_headers. Simply a
# whitespace delimited list of header names and names can optionally end with
# '*' to indicate a prefix match.
default['openstack']['object-storage']['tempurl']['outgoing_allow_headers'] = 'x-object-meta-public-*'

# enable or disable domain_remap
default['openstack']['object-storage']['domain_remap']['enabled'] = false

# enable domain log name
default['openstack']['object-storage']['domain_remap']['log_name'] = 'domain_remap'

# domain remap log facilty
default['openstack']['object-storage']['domain_remap']['log_facility'] = 'LOG_LOCAL0'

# domain remap log level
default['openstack']['object-storage']['domain_remap']['log_level'] = 'INFO'

# domain remap log headers
default['openstack']['object-storage']['domain_remap']['log_headers'] = 'False'

# domain remap reseller domain
default['openstack']['object-storage']['domain_remap']['storage_domain'] = 'example.com'

# domain remap root path
default['openstack']['object-storage']['domain_remap']['path_root'] = 'v1'

# domain remap reseller prefixes
default['openstack']['object-storage']['domain_remap']['reseller_prefixes'] = 'AUTH'

# whether or not to enable staticweb in the swift proxy
default['openstack']['object-storage']['staticweb']['enabled'] = false

# Seconds to cache container x-container-meta-web-* header values.
default['openstack']['object-storage']['staticweb']['cache_timeout'] = 300

# staticweb logging options
default['openstack']['object-storage']['staticweb']['log_facility'] = 'LOG_LOCAL0'
default['openstack']['object-storage']['staticweb']['log_level'] = 'INFO'
default['openstack']['object-storage']['staticweb']['access_log_name'] = 'staticweb'
default['openstack']['object-storage']['staticweb']['access_log_facility'] = 'LOG_LOCAL0'
default['openstack']['object-storage']['staticweb']['access_log_level'] = 'INFO'
default['openstack']['object-storage']['staticweb']['log_headers'] = 'False'

# container-server

# Use an integer to override the number of pre-forked processes that will
# accept connections.  Zero means no fork. Should default to the number of
# effective cpu cores in the system.  It's worth noting that individual
# workers will # use many eventlet co-routines to service multiple concurrent
# requests.
default['openstack']['object-storage']['container-server']['workers'] = 'auto'

# Maximum number of clients one worker can process simultaneously (it will
# actually accept(2) N + 1). Setting this to one (1) will only handle one request
# at a time, without accepting another request concurrently.  The default is 1024.
default['openstack']['object-storage']['container-server']['max_clients'] = 1024

# Parent directory or where devices are mounted. Default is /srv/node
default['openstack']['object-storage']['container-server']['devices'] = '/srv/node'

# Whether or not check if the devices are mounted to prevent accidentally writing to
# the root device. The default is set to true.
default['openstack']['object-storage']['container-server']['mount_check'] = true

# Override this with an allowed list of your various swift clusters if you wish
# to enable container sync for your end-users between clusters.  This should
# be an array of fqdn hostnames for the cluster end-points that your end-users
# would access in the format of ['host1', 'host2', 'host3']
default['openstack']['object-storage']['container-server']['allowed_sync_hosts'] = []

# container-sync logging settings
default['openstack']['object-storage']['container-server']['container-sync']['log_name'] = 'container-sync'
default['openstack']['object-storage']['container-server']['container-sync']['log_facility'] = 'LOG_LOCAL0'
default['openstack']['object-storage']['container-server']['container-sync']['log_level'] = 'INFO'

# If you need to use an HTTP Proxy, set it here; defaults to no proxy.
default['openstack']['object-storage']['container-server']['container-sync']['sync_proxy'] = nil

# Will sync, at most, each container once per interval (in seconds)
default['openstack']['object-storage']['container-server']['container-sync']['interval'] = 300

# Maximum amount of time to spend syncing each container per pass (in seconds)
default['openstack']['object-storage']['container-server']['container-sync']['container_time'] = 60

# object-server

# Use an integer to override the number of pre-forked processes that will
# accept connections.  Zero means no fork. Should default to the number of
# effective cpu cores in the system.  It's worth noting that individual
# workers will # use many eventlet co-routines to service multiple concurrent
# requests.
default['openstack']['object-storage']['object-server']['workers'] = 'auto'

# Maximum number of clients one worker can process simultaneously (it will
# actually accept(2) N + 1). Setting this to one (1) will only handle one request
# at a time, without accepting another request concurrently.  The default is 1024.
default['openstack']['object-storage']['object-server']['max_clients'] = 1024

# Parent directory or where devices are mounted. Default is /srv/node
default['openstack']['object-storage']['object-server']['devices'] = '/srv/node'

# Whether or not check if the devices are mounted to prevent accidentally writing to
# the root device. The default is set to true.
default['openstack']['object-storage']['object-server']['mount_check'] = true

# Time in seconds to wait between replication passes. The default is 30.
default['openstack']['object-storage']['object-server']['replicator']['run_pause'] = 30

# Time elapsed in seconds before an object can be reclaimed. The default is
# 604800 seconds.
default['openstack']['object-storage']['object-server']['replicator']['reclaim_age'] = 604800

#------------------
# swauth source
# -----------------
# Versions of swauth in Ubuntu Cloud Archive PPA can be outdated. This
# allows us to chose to install directly from a tagged branch of
# gholt's repository.
# values:  package, git
default['openstack']['object-storage']['swauth_source'] = 'package'
default['openstack']['object-storage']['swauth_repository'] = 'https://github.com/gholt/swauth.git'
default['openstack']['object-storage']['swauth_version'] = '1.0.8'

#------------------
# packages
#------------------

# Leveling between distros
case platform_family
when 'rhel'
  default['openstack']['object-storage']['platform'] = {
    'disk_format' => 'ext4',
    'proxy_packages' => %w(openstack-swift-proxy sudo cronie python-memcached),
    'object_packages' => ['openstack-swift-object', 'sudo', 'cronie'],
    'container_packages' => ['openstack-swift-container', 'sudo', 'cronie'],
    'account_packages' => ['openstack-swift-account', 'sudo', 'cronie'],
    'swift_packages' => ['openstack-swift', 'sudo', 'cronie'],
    'swift_client_packages' => ['python-swiftclient'],
    'swauth_packages' => ['openstack-swauth', 'sudo', 'cronie'],
    'rsync_packages' => ['rsync'],
    'git_packages' => ['xinetd', 'git', 'git-daemon'],
    'service_prefix' => 'openstack-',
    'service_suffix' => '',
    'git_dir' => '/var/lib/git',
    'git_service' => 'git',
    'override_options' => '',
    'swift_statsd_publish' => '/usr/bin/swift-statsd-publish.py'
  }
when 'debian'
  default['openstack']['object-storage']['platform'] = {
    'disk_format' => 'xfs',
    'proxy_packages' => ['swift-proxy', 'python-memcache'],
    'object_packages' => ['swift-object'],
    'container_packages' => ['swift-container'],
    'account_packages' => ['swift-account', 'python-swiftclient'],
    'swift_packages' => ['swift'],
    'swift_client_packages' => ['python-swiftclient'],
    'swauth_packages' => ['swauth'],
    'rsync_packages' => ['rsync'],
    'git_packages' => ['git-daemon-sysvinit'],
    'service_prefix' => '',
    'service_suffix' => '',
    'git_dir' => '/var/cache/git',
    'git_service' => 'git-daemon',
    'override_options' => "-o Dpkg::Options:='--force-confold' -o Dpkg::Option:='--force-confdef'",
    'swift_statsd_publish' => '/usr/local/bin/swift-statsd-publish.py'
  }
end
